// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import Apple from '@/shared/assets/icons/apple.svg';
import Ban from '@/shared/assets/icons/ban.svg';
import BusSelected from '@/shared/assets/icons/bus-selected.svg';
import Bus from '@/shared/assets/icons/bus.svg';
import CalendarIcon from '@/shared/assets/icons/calendar-icon.svg';
import CalendarNeutral from '@/shared/assets/icons/calendar-neutral.svg';
import CalendarPrimary from '@/shared/assets/icons/calendar-primary.svg';
import Calendar from '@/shared/assets/icons/calendar.svg';
import Camera from '@/shared/assets/icons/camera.svg';
import CarSelected from '@/shared/assets/icons/car-selected.svg';
import Car from '@/shared/assets/icons/car.svg';
import CaretDown from '@/shared/assets/icons/caret-down.svg';
import CaretUp from '@/shared/assets/icons/caret-up.svg';
import Check from '@/shared/assets/icons/check.svg';
import ChevronDown from '@/shared/assets/icons/chevron-down.svg';
import ChevronLeft from '@/shared/assets/icons/chevron-left.svg';
import ChevronRight from '@/shared/assets/icons/chevron-right.svg';
import ChevronSmallLeft from '@/shared/assets/icons/chevron-small-left.svg';
import ChevronSmallRight from '@/shared/assets/icons/chevron-small-right.svg';
import ChevronUp from '@/shared/assets/icons/chevron-up.svg';
import CircleInformation from '@/shared/assets/icons/circle-information.svg';
import Clock from '@/shared/assets/icons/clock.svg';
import Close from '@/shared/assets/icons/close.svg';
import Confetti from '@/shared/assets/icons/confetti.svg';
import Edit from '@/shared/assets/icons/edit.svg';
import Envelope from '@/shared/assets/icons/envelope.svg';
import Error from '@/shared/assets/icons/error.svg';
import EyeOff from '@/shared/assets/icons/eye-off.svg';
import Eye from '@/shared/assets/icons/eye.svg';
import Feedback from '@/shared/assets/icons/feedback.svg';
import Group from '@/shared/assets/icons/group.svg';
import Invitation from '@/shared/assets/icons/invitation.svg';
import KakaoLogo from '@/shared/assets/icons/kakao-logo.svg';
import KakaoText from '@/shared/assets/icons/kakao-text.svg';
import Kakao from '@/shared/assets/icons/kakao.svg';
import Kebab from '@/shared/assets/icons/kebab.svg';
import LinkSmall from '@/shared/assets/icons/link-small.svg';
import Link from '@/shared/assets/icons/link.svg';
import LocationNeutral from '@/shared/assets/icons/location-neutral.svg';
import LocationPrimary from '@/shared/assets/icons/location-primary.svg';
import Location from '@/shared/assets/icons/location.svg';
import Lock from '@/shared/assets/icons/lock.svg';
import LogOut from '@/shared/assets/icons/log-out.svg';
import Minus from '@/shared/assets/icons/minus.svg';
import MoyeoLogoPlaceholder from '@/shared/assets/icons/moyeo-logo-placeholder.svg';
import MoyeoLogo from '@/shared/assets/icons/moyeo-logo.svg';
import NotePrimary from '@/shared/assets/icons/note-primary.svg';
import Note from '@/shared/assets/icons/note.svg';
import Person from '@/shared/assets/icons/person.svg';
import PinnedPrimary from '@/shared/assets/icons/pinned-primary.svg';
import Pinned from '@/shared/assets/icons/pinned.svg';
import Plane from '@/shared/assets/icons/plane.svg';
import Plus from '@/shared/assets/icons/plus.svg';
import Search from '@/shared/assets/icons/search.svg';
import Undo from '@/shared/assets/icons/undo.svg';

export const ICONS = {
  apple: Apple,
  ban: Ban,
  'bus-selected': BusSelected,
  bus: Bus,
  'calendar-icon': CalendarIcon,
  'calendar-neutral': CalendarNeutral,
  'calendar-primary': CalendarPrimary,
  calendar: Calendar,
  camera: Camera,
  'car-selected': CarSelected,
  car: Car,
  'caret-down': CaretDown,
  'caret-up': CaretUp,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-small-left': ChevronSmallLeft,
  'chevron-small-right': ChevronSmallRight,
  'chevron-up': ChevronUp,
  'circle-information': CircleInformation,
  clock: Clock,
  close: Close,
  confetti: Confetti,
  edit: Edit,
  envelope: Envelope,
  error: Error,
  'eye-off': EyeOff,
  eye: Eye,
  feedback: Feedback,
  group: Group,
  invitation: Invitation,
  'kakao-logo': KakaoLogo,
  'kakao-text': KakaoText,
  kakao: Kakao,
  kebab: Kebab,
  'link-small': LinkSmall,
  link: Link,
  'location-neutral': LocationNeutral,
  'location-primary': LocationPrimary,
  location: Location,
  lock: Lock,
  'log-out': LogOut,
  minus: Minus,
  'moyeo-logo-placeholder': MoyeoLogoPlaceholder,
  'moyeo-logo': MoyeoLogo,
  'note-primary': NotePrimary,
  note: Note,
  person: Person,
  'pinned-primary': PinnedPrimary,
  pinned: Pinned,
  plane: Plane,
  plus: Plus,
  search: Search,
  undo: Undo,
} as const;

export type IconName = keyof typeof ICONS;
