// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import Apple from '@/shared/assets/icons/apple.svg';
import Avatar from '@/shared/assets/icons/avatar.svg';
import CalendarPrimary from '@/shared/assets/icons/calendar-primary.svg';
import Calendar from '@/shared/assets/icons/calendar.svg';
import CaretDown from '@/shared/assets/icons/caret-down.svg';
import CaretUp from '@/shared/assets/icons/caret-up.svg';
import Check from '@/shared/assets/icons/check.svg';
import ChevronDown from '@/shared/assets/icons/chevron-down.svg';
import ChevronLeft from '@/shared/assets/icons/chevron-left.svg';
import ChevronRight from '@/shared/assets/icons/chevron-right.svg';
import ChevronSmallLeft from '@/shared/assets/icons/chevron-small-left.svg';
import ChevronSmallRight from '@/shared/assets/icons/chevron-small-right.svg';
import ChevronUp from '@/shared/assets/icons/chevron-up.svg';
import Close from '@/shared/assets/icons/close.svg';
import Envelope from '@/shared/assets/icons/envelope.svg';
import KakaoLogo from '@/shared/assets/icons/kakao-logo.svg';
import Kakao from '@/shared/assets/icons/kakao.svg';
import LinkSmall from '@/shared/assets/icons/link-small.svg';
import Link from '@/shared/assets/icons/link.svg';
import Minus from '@/shared/assets/icons/minus.svg';
import NotePrimary from '@/shared/assets/icons/note-primary.svg';
import Note from '@/shared/assets/icons/note.svg';
import PinnedPrimary from '@/shared/assets/icons/pinned-primary.svg';
import Pinned from '@/shared/assets/icons/pinned.svg';
import Plus from '@/shared/assets/icons/plus.svg';

export const ICONS = {
  apple: Apple,
  avatar: Avatar,
  'calendar-primary': CalendarPrimary,
  calendar: Calendar,
  'caret-down': CaretDown,
  'caret-up': CaretUp,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-small-left': ChevronSmallLeft,
  'chevron-small-right': ChevronSmallRight,
  'chevron-up': ChevronUp,
  close: Close,
  envelope: Envelope,
  'kakao-logo': KakaoLogo,
  kakao: Kakao,
  'link-small': LinkSmall,
  link: Link,
  minus: Minus,
  'note-primary': NotePrimary,
  note: Note,
  'pinned-primary': PinnedPrimary,
  pinned: Pinned,
  plus: Plus,
} as const;

export type IconName = keyof typeof ICONS;
